### ISSUE TITLE
Small sprite rotation raises ZeroDivisionError

### ISSUE THREAD

**Issue by tmontes** [tmontes/python-aturtle#40]
### Context

Discovered while implementing sync animation.

### Reproduction

```
import aturtle, easing_functions

w = aturtle.Window(height=800, x=800, y=50)
sh = aturtle.shapes.vector.Star(radius=24)
s = aturtle.create_sprite(w.canvas, sh, update=True)
s.sync_rotate(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<generated>", line 28, in sync_rotate
ZeroDivisionError: division by zero
```

**Comment by tmontes** [comment]
Fixed with #47, which also addresses other high-speed / low-fps failing animation cases.
