### ISSUE TITLE
Bitmap sprite rotation around non-anchor fails with Tk 8.4

### ISSUE THREAD

**Issue by tmontes** [tmontes/python-aturtle#42]
### Reproduction

Python linked against Tk 8.4

```
import aturtle

w = aturtle.Window()
s = aturtle.create_sprite(w.canvas, 'sprite.png')
s.rotate(90, around=(-50, 50))
```

Leads to the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tmontes/Work/python-aturtle/src/aturtle/sprites/bitmap.py", line 43, in rotate
    self._canvas.moveto(
  File "/Users/tmontes/usr/local/python-3.8.1/lib/python3.8/tkinter/__init__.py", line 2924, in moveto
    self.tk.call(self._w, 'moveto', tagOrId, x, y)
_tkinter.TclError: bad option "moveto": must be addtag, bbox, bind, canvasx, canvasy, cget, configure, coords, create, dchars, delete, dtag, find, focus, gettags, icursor, index, insert, itemcget, itemconfigure, lower, move, postscript, raise, scale, scan, select, type, xview, or yview
```

### Motive

Guessing that Tk 8.4's `Canvas` objects to not handle the `moveto` operation.

### Way forward

* Ignore, given that Tk 8.4 is old.
* Change `rotate` implementation to be based on `Canvas.move` operations.

**Comment by tmontes** [comment]
Confirmation:
* `Canvas.moveto` was introduced in Tk 8.6 as documented in https://www.tcl.tk/software/tcltk/8.6.html.

**Comment by tmontes** [comment]
Confirmed that #43 refactor fixed this, given that `Canvas.moveto` is no longer used.
Closing.
